services:
  - type: web
    name: task-tracker-backend
    runtime: node
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in Render dashboard:
    # - MONGODB_URI (your MongoDB Atlas connection string)
    # - JWT_SECRET (a secure random string)
    # - CLOUDINARY_CLOUD_NAME
    # - CLOUDINARY_API_KEY  
    # - CLOUDINARY_API_SECRET
    # - FRONTEND_URL (will be your Vercel frontend URL)
